version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nftdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - app-network

  event_listener:
    build:
      context: .
      dockerfile: Dockerfile
    image: nftproj-event-listener
    env_file: .env
    restart: unless-stopped
    depends_on:
      - kafka
      - postgres
    networks:
      - app-network

  metadata_worker:
    build:
      context: .
      dockerfile: metadata_worker/Dockerfile
    image: nftproj-metadata-worker
    env_file: .env
    restart: unless-stopped
    depends_on:
      - kafka
      - postgres
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: nftproj-api
    env_file: .env
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    command: ["cargo", "run", "--release", "-p", "api"]
    networks:
      - app-network

  backfill-script:
    build:
      context: .
      dockerfile: backfill_script/Dockerfile
    env_file: .env
    depends_on:
      - kafka
      - metadata_worker
    restart: "no"
    networks:
      - app-network

  frontend:
    build:
      context: ./artverse-archive
      dockerfile: Dockerfile
    image: nftproj-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://api:3000
    depends_on:
      - api
    volumes:
      - ./artverse-archive:/app
      - /app/node_modules
    networks:
      - app-network

volumes:
  postgres-data: 